services:
  
  valheim:
    
    image: ghcr.io/community-valheim-tools/valheim-server
    container_name: valheim-server
    restart: unless-stopped

    env_file:
      - /srv/docker/valheim-server/tyrisol.env
      - /srv/docker/valheim-server/password.env
    
    ports:
      - "2456-2457:2456-2457/udp"

    volumes:
      - /srv/docker/valheim-server/config:/config
      - /srv/data/valheim-server/data:/opt/valheim
    
    stop_grace_period: 2m  # Gives the server plenty of time to save the world before closing

